import turtle

turtle.penup()
turtle.goto(-200,0)
turtle.pendown()
turtle.right(60)
turtle.circle(50, steps=3)
turtle.penup()
turtle.goto(-100,0)
turtle.left(60)
turtle.pendown()
turtle.right(45)
turtle.circle(50, steps=4)
turtle.penup()
turtle.goto(0,0)
turtle.left(45)
turtle.right(36)
turtle.pendown()
turtle.circle(50, steps=5)
turtle.penup()
turtle.goto(110,0)
turtle.left(36)
turtle.right(30)
turtle.pendown()
turtle.circle(50, steps=6)
turtle.penup()
turtle.goto(225,0)
turtle.left(30)
turtle.right(22.5)
turtle.pendown()
turtle.circle(50, steps=8)

turtle.done()