import turtle
x,y = eval(input("Enter center of rectangle in x,y : "))
width, height = eval(input("Enter width and height : "))
turtle.penup()
turtle.goto(x-(width/2),y+(height/2))
turtle.pendown()
turtle.goto(x+(width/2),y+(height/2))
turtle.goto(x+(width/2),y-(height/2))
turtle.goto(x-(width/2),y-(height/2))
turtle.goto(x-(width/2),y+(height/2))
turtle.penup()
turtle.goto(x,y)
turtle.done()
